name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag circle:$(date +%s) .
    
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        path: /home/runner/work/SorenaMorr/SorenaMorr

    
    - name: Upload image
      uses: McCzarny/upload-image@cfbca06cc6bde914bda8d13d3ccb7885d40e9b25
      with:
        path: /home/runner/work/SorenaMorr/SorenaMorr
        uploadMethod: https://hub.docker.com/repository/docker/sorena2004/devops-test
